### ISSUE TITLE
Build error with  grid_map::PolygonRosConverter::toTriangleListMarker

### ISSUE THREAD

**Issue by gehrinch** [leggedrobotics/free_gait#31]
I get the following build error: 

`Errors     << free_gait_ros:make /home/gehrinch/catkin_ws/logs/free_gait_ros/build.make.000.log                                                                                                                                         
/home/gehrinch/catkin_ws/src/free_gait/free_gait_ros/src/RosVisualization.cpp: In static member function ‘static const Marker free_gait::RosVisualization::getStanceMarker(const Stance&, const string&, const ColorRGBA&)’:
/home/gehrinch/catkin_ws/src/free_gait/free_gait_ros/src/RosVisualization.cpp:39:3: error: ‘toTriangleListMarker’ is not a member of ‘grid_map::PolygonRosConverter’
   grid_map::PolygonRosConverter::toTriangleListMarker(polygon, color, height, marker);
   ^
make[2]: *** [CMakeFiles/free_gait_ros.dir/src/RosVisualization.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/free_gait_ros.dir/all] Error 2
make: *** [all] Error 2
cd /home/gehrinch/catkin_ws/build/free_gait_ros; catkin build --get-env free_gait_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
........................................................................................................................................................................................................................................
Failed     << free_gait_ros:make                                     [ Exited with code 2 ]                                                                                                                                             
Failed    <<< free_gait_ros                                          [ 50.1 seconds ]                                                                                                                                                   
Abandoned <<< anymal_highlevel_contro`

I cleaned everything in the catkin workspace and pulled everything.

**Comment by pfankhauser** [comment]
You seem to be on an old version of Grid Map. Make sure to update to the latest version.
